### ISSUE TITLE
SOFT block parse issue

### ISSUE THREAD

**Issue by yao-baijian** [AugustUnderground/pygsrc#2]
Hi August
I was testing with SOFT block n10, and I found block2corners trying to parser Vertex coordinates even with SOFT block. I have attached my debug info here. 
![未命名图片](https://github.com/user-attachments/assets/9683d24e-7320-4c0c-9c99-12920d5d51df)
I can add soft block_size part if you need

**Comment by AugustUnderground** [comment]
Hi Yao,

thanks for finding this. If you have a fix in mind please go ahead, I'd appreciate it. Do soft blocks have a default, or how would you implement this? What is `block_size` going to be?

**Comment by yao-baijian** [comment]
sry for the late reply, I just take a deep look into your code, and found out block_size represent x-y width. I dont know if gsrc soft block data format like (module name, module type, area size, x-y ratio, height) since I can not access  http://vlsicad.eecs.umich.edu/BK/GSRCbench/ now. I let code read in x-y ratio. Let me know if I am wrong, you can easily change the code to read in x-y ratio, height as well

**Comment by AugustUnderground** [comment]
I must admit, I've never really looked at the soft blocks in the data set myself. So, I think we should do it in a way that makes sense for you in practice. 

If the dictionary with width and height for `block_size` doesn't make sense here, we could add a new field `'ratio'` and read that in. Is that what you are doing now? Or are you computing a width and height based on the ratio and a given default?
